idf_component_register(
    SRCS "src/main.cpp"
         "src/system/Logger.cpp"
         "src/system/SystemManager.cpp"
         "src/communication/NetworkManager.cpp"
    INCLUDE_DIRS "include"
    REQUIRES "esp_wifi"
             "nvs_flash"
             "mqtt"
             "driver"
             "esp_event"
             "esp_netif"
             "log"
             "freertos"
)
