idf_component_register(
    SRCS "src/main.cpp"
         "src/system/Logger.cpp"
         "src/system/SystemManager.cpp"
         "src/communication/NetworkManager.cpp"
         "src/sensors/Environment/DHTSensor.cpp"
         "src/sensors/Environment/MQ137Sensor.cpp"
         "src/sensors/Environment/BH1750Sensor.cpp"
         "src/sensors/Environment/SHT31Sensor.cpp"
         "src/sensors/Resource/FeedLevelSensor.cpp"
         "src/sensors/Security/PIRSensor.cpp"
         "src/sensors/Health/ThermalCamera.cpp"
    INCLUDE_DIRS "include"
                 "include/sensors/Environment"
                 "include/sensors/Resource"
                 "include/sensors/Health"
                 "include/sensors/Security"
                 "include/sensors/Operation"
    REQUIRES "esp_wifi"
             "nvs_flash"
             "mqtt"
             "driver"
             "esp_event"
             "esp_netif"
             "log"
             "freertos"
)
